# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Entity\User: bcrypt

    providers:
        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        api_doc:
            pattern: ^/api/doc
            security: false
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/users, roles: ROLE_ADMIN }
