
parameters:
    user.class: AppBundle\Entity\User
    user.provider.class: AppBundle\Security\Provider\UserProvider

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    user.provider:
        class: '%user.provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%user.class%'
